spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3000/traffic?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:initializeDatabase/schema.sql
